### ISSUE TITLE
Error when trying to join consultation using web site

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#125]
**Describe the bug**
Can't join ongoing consultation from both client and provider side. 
Was using - https://usupport.online/provider/dashboard
and -  https://usupport.online/client/

**To Reproduce**
1. Create an open consultation slot
2. Click join
3. See error
(same form client side)

**Expected behavior**
Ability to join consultation 

**Screenshots**
-Provider side
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/30b26179-a117-4e10-8e0d-d7c239228e00)
- Client side
![client](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/ddc358da-8867-473f-9a3d-457f18017fae)

**Desktop (provider):**
 - OS: windows 10
 - Browser  chrome
 - Version latest

**Smartphone (client):**
 - Device: Xiaomi redmi 10s
 - OS: Android 13
 - Browser Google chrome
 - Version latest

**Additional context**
Although it was impossible to join from browser on both sides, joining form the phone using application worked just fine

**Comment by sebastian-7DIGIT** [comment]
@fomap The issue described above should be fixed now. Kindly asking if you could test it again on your end and report your findings to us.

**Comment by fomap** [comment]
Although I was able to connect to consultation from both client and provider side there were still couple of issues. 
1) As provider I was not able to see/hear client, however client was able to see themselves. 
2) Client was also not able to see/hear me but from my side there was absence of image as well. Toggle buttons on camera and mic don't seem to respond to input
*Text chat works as intended
*Devices stayed the same: Desktop for provider and mobile phone for client
Sending screenshots from client:
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/b9341b0b-04b3-4e7a-a117-a36f71fc111d)
and provider sides:
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/a0f9d128-a0a1-4d5e-a31b-99a55093c2fb)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych this issue can be closed.

**Comment by Gaskevych** [comment]
It seems @fomap has experienced the same challelnge recently while retesting the consultation from mobile app. @fomap please confirm?

**Comment by fomap** [comment]
The issue still persists. It continues to work as intended only after provider joins through text consultation and turns on camera and microphone using toggle buttons. 
![when joining nothing workds](https://github.com/user-attachments/assets/09ea59ae-71e4-4057-b18a-af642ee1a1e0)


There is also issue when trying to rejoin consultation (only for web) 
Provider side:
![error when trying to regoin consulatiaon](https://github.com/user-attachments/assets/3f5db76a-52f9-4fd1-814d-10fd01c960bb)
 Client side:
![image](https://github.com/user-attachments/assets/17e42fd1-1d8b-4879-80ab-2a43d6a3a776)

**Comment by Gaskevych** [comment]
I will close this issue as we are moving to Jitsi
